package eu.japtor.vizman.backend.entity;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a Person
 */
@Entity
@Table(name = "PERSON")
public class Person extends AbstractEntity {

    //    @Column(name="STATUS")
    @Enumerated(EnumType.STRING)
    private PersonStatus status = PersonStatus.NEW;
    public PersonStatus getStatus() {
        return status;
    }
    public void setStatus(PersonStatus status) {
        this.status = status;
    }

    //    @Column(name="USERNAME")
    private String username = "";
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    //    @Column(name="PASSWORD")
    private String password = "";
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

//    @Column(name="JMENO")
    private String jmeno = "";
    public String getJmeno() {
        return jmeno;
    }
    public void setJmeno(String jmeno) {
        this.jmeno = jmeno;
    }

    //    @Column(name="PRIJMENI")
    private String prijmeni = "";
    public String getPrijmeni() {
        return prijmeni;
    }
    public void setPrijmeni(String prijmeni) {
        this.prijmeni = prijmeni;
    }

    //    @Column(name="NASTUP")
//    @Temporal(TemporalType.TIMESTAMP)
    private LocalDate nastup;
    public LocalDate getNastup() {
        return nastup;
    }
    public void setNastup(LocalDate nastup) {
        this.nastup = nastup;
    }

//    @Column(name="VYSTUP")
//    @Temporal(TemporalType.TIMESTAMP)
    private LocalDate vystup;
    public LocalDate getVystup() {
        return vystup;
    }
    public void setVystup(LocalDate vystup) {
        this.vystup = vystup;
    }

    //    @Column(name="SAZBA")
    private BigDecimal sazba = BigDecimal.ZERO;
    public BigDecimal getSazba() {
        return sazba;
    }
    public void setSazba(BigDecimal sazba) {
        this.sazba = sazba;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "person_role",
            joinColumns = @JoinColumn(
                    name = "person_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(
                    name = "role_id", referencedColumnName = "id"))
    private Set<Role> roles;
    public Set<Role> getRoles() {
        return roles;
    }
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public Person() {
        roles = new HashSet<>();
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Person{" + getId()  + " : " + getUsername() + " : " + getJmeno() + " " + getPrijmeni() + '}';
    }
}
