package eu.japtor.vizman.backend.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Represents a Usr
 */
@Entity
@Table(name = "USR")
public class Usr extends AbstractEntity {

    @Column(name="PASSWORD")
    private String password = "";

    @Column(name="USERNAME")
    private String username = "";
    @Column(name="FIRST_NMAME")
    private String firstName = "";

    @Column(name="LAST_NAME")
    private String lastName = "";


    public Usr() {
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Sets the value username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Usr{" + getId() + ":" + getPassword() + ":" + getUsername() + '}';
    }
}
