package eu.japtor.vizman.backend.entity;

import org.springframework.security.access.annotation.Secured;

import javax.persistence.*;
import java.util.Collection;
import java.util.Set;

/**
 * Represents a Usr
 */
@Entity
//@Table(name = "USR")
public class Usr extends AbstractEntity {

//    @Column(name="PASSWORD")
    private String password = "";

//    @Column(name="USERNAME")
    private String username = "";
//    @Column(name="FIRST_NMAME")
    private String firstName = "";

//    @Column(name="LAST_NAME")
    private String lastName = "";

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "usr_role",
            joinColumns = @JoinColumn(
                    name = "usr_id", referencedColumnName = "id"),
            inverseJoinColumns = @JoinColumn(
                    name = "role_id", referencedColumnName = "id"))
    private Set<Role> roles;

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public Usr() {
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Usr{" + getId() + ":" + getPassword() + ":" + getUsername() + '}';
    }
}
