package eu.japtor.vizman.backend.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Represents a Usr
 */
@Entity
@Table(name = "USER")
public class Usr extends AbstractEntity {

    @Column(name="PASSWORD")
    private String password = "";

    @Column(name="USERNAME")
    private String username = "";

    public Usr() {
    }

    /**
     * Gets the value of password
     *
     * @return the value of user password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value password
     *
     * @param password new value of user password
     */
    public void setPassword(String password) {
        this.password = password;
    }


    /**
     * Gets the value of user username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Usr{" + getId() + ":" + getPassword() + ":" + getUsername() + '}';
    }
}
