package eu.japtor.vizman.backend.entity;

import javax.persistence.*;

/**
 * Represents a zakazka
 */
@Entity
//@Table(name = "ZAK")
public class Zak extends AbstractEntity {

    @Column(name="ZAK_NUM")
    private String zakNum = "";

    @Column(name="ZAK_TITLE")
    private String zakTitle = "";

    public Zak() {
    }

    /**
     * Gets the value of zakNum
     *
     * @return the value of zak number
     */
    public String getZakNum() {
        return zakNum;
    }

    /**
     * Sets the value zakNum
     *
     * @param zakNum new value of zak number
     */
    public void setZakNum(String zakNum) {
        this.zakNum = zakNum;
    }


    /**
     * Gets the value of zak title
     *
     * @return the value of zakTitle
     */
    public String getZakTitle() {
        return zakTitle;
    }

    /**
     * Sets the value zakTitle
     *
     * @param zakTitle new value of zak title
     */
    public void setZakTitle(String zakTitle) {
        this.zakTitle = zakTitle;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "Zakázka{" + getId() + ":" + getZakNum() + ":" + getZakTitle() + '}';
    }
}
