package eu.japtor.vizman.backend.entity;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * Represents a Person
 */
@Entity
@Table(name = "ZAQA")
public class Zaqa extends AbstractGenIdEntity implements HasItemType {

    public static final GrammarGender GENDER = GrammarGender.MASCULINE;

    @Column(name="ROK")
    private Integer rok;

    @Column(name="QA")
    private Integer qa;

    @Column(name="RX")
    private BigDecimal rx;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_ZAK")
    private Zakr zakr;


// -----------------------------------------------------


    public Integer getRok() {
        return rok;
    }
    public void setRok(Integer rok) {
        this.rok = rok;
    }

    public Integer getQa() {
        return qa;
    }
    public void setQa(Integer qa) {
        this.qa = qa;
    }

    public BigDecimal getRx() {
        return rx;
    }
    public void setRx(BigDecimal rx) {
        this.rx = rx;
    }

    public Zakr getZakr() {
        return zakr;
    }
    public void setZakr(Zakr zakr) {
        this.zakr = zakr;
    }

    @Override
    public String toString() {
        // Must use getters instead of direct member access,
        // to make it work with proxy objects generated by the view model
        return "RX {" + getId()  + " : " + getRok() + " : " + getQa() + " : " + getRx()  + '}';
    }

    @Override
    @Transient
    public ItemType getTyp() {
        return ItemType.UNKNOWN;
    }
}
