

INSERT INTO VIZMAN.CIN
(ID, VERSION, PORADI, AKCE_TYP, AKCE, CIN_KOD, CINNOST, CALCPRAC, TMP)
VALUES(14, 1, 35, 'F', 'Služebka (celý den)', 'SC', 'Služebka', true, NULL)
;

COMMIT;


-- CREATE OR REPLACE VIEW VIZMAN.ZAK_BASIC_VIEW AS
--	SELECT zak.ID, zak.TYP, kont.CKONT, zak.CZAK, zak.ROK, zak.SKUPINA, kont.TEXT AS TEXT_KONT, zak.TEXT AS TEXT_ZAK, kont.OBJEDNATEL, zak.ARCH, zak.ID_KONT
--	FROM VIZMAN.ZAK zak
--	LEFT JOIN VIZMAN.KONT kont ON zak.ID_KONT = kont.ID
--;


UPDATE vizman.CIN
	SET AKCE_TYP = 'F'
	WHERE CIN_KOD = 'dc'
;

COMMIT;


CREATE OR REPLACE VIEW VIZMAN.ZAK_BASIC_VIEW AS
	SELECT zak.ID, zak.TYP, kont.CKONT, zak.CZAK, zak.ROK, zak.SKUPINA, kont.TEXT AS TEXT_KONT, zak.TEXT AS TEXT_ZAK, klient.NAME AS OBJEDNATEL, zak.ARCH, zak.ID_KONT
	FROM VIZMAN.ZAK zak
	LEFT JOIN VIZMAN.KONT kont ON zak.ID_KONT = kont.ID
	LEFT JOIN VIZMAN.KLIENT klient ON kont.ID_KLIENT = klient.ID
;


ALTER TABLE VIZMAN.FAKT
	ADD COLUMN FAKT_CISLO Varchar(40)
;

ALTER TABLE VIZMAN.FAKT
	MODIFY COLUMN FAKT_CISLO Varchar(40)
;

ALTER TABLE VIZMAN.KONT
	MODIFY COLUMN ROK INTEGER
;

ALTER TABLE VIZMAN.ZAK
	ADD COLUMN POZNAMKA Varchar(127)
;

SELECT username, DOCH_DATE
FROM VIZMAN.DOCH
WHERE DOCH_DATE >= '2019-01-01'
AND CIN_CIN_KOD = 'L'
;

ALTER TABLE VIZMAN.KONT
	MODIFY COLUMN FOLDER Varchar(140)
;

ALTER TABLE VIZMAN.ZAK
	MODIFY COLUMN FOLDER Varchar(140)
;



ALTER TABLE VIZMAN.KONT
	MODIFY COLUMN FOLDER NOT NULL
;

ALTER TABLE VIZMAN.ZAK
	MODIFY COLUMN FOLDER NOT NULL
;


ALTER TABLE VIZMAN.ZAK
	MODIFY COLUMN ROK INTEGER
;


CREATE OR REPLACE VIEW VIZMAN.ZAK_ROZPRAC_VIEW AS
	SELECT zak.ID, zak.TYP, kont.CKONT, zak.CZAK, zak.ROK, zak.SKUPINA, kont.TEXT AS TEXT_KONT, zak.TEXT AS TEXT_ZAK, klient.NAME AS OBJEDNATEL, zak.ARCH, zak.ID_KONT,
	       zak.ROZPRAC as R0, zak.R1, zak.R2, zak.R3, zak.R4
	FROM VIZMAN.ZAK zak
	LEFT JOIN VIZMAN.KONT kont ON zak.ID_KONT = kont.ID
	LEFT JOIN VIZMAN.KLIENT klient ON kont.ID_KLIENT = klient.ID
;

COMMIT;


CREATE OR REPLACE FORCE VIEW VIZMAN.ZAK_ROZPRAC_VIEW(
	ID, TYP, CKONT, CZAK, ROK, SKUPINA, TEXT_KONT, TEXT_ZAK, OBJEDNATEL, ARCH, ID_KONT,
	R0, R1, R2, R3, R4,
	HONOR_CISTY, HONOR_FAKT, HONOR_SUB
) AS
SELECT zak.ID,
    zak.TYP,
    KONT.CKONT,
    zak.CZAK,
    zak.ROK,
    zak.SKUPINA,
    KONT.TEXT AS TEXT_KONT,
    zak.TEXT AS TEXT_ZAK,
    KLIENT.NAME AS OBJEDNATEL,
    zak.ARCH,
    zak.ID_KONT,
    zak.ROZPRAC AS R0,
    zak.R1,
    zak.R2,
    zak.R3,
    zak.R4,
	SUM(fakta.CASTKA) AS HONOR_CISTY,
	SUM(faktb.CASTKA) AS HONOR_FAKT,
	SUM(faktc.CASTKA) AS HONOR_SUB	
FROM vizman.ZAK zak
LEFT OUTER JOIN vizman.FAKT fakta
	on fakta.id_zak = zak.id
LEFT OUTER JOIN vizman.FAKT faktb
	on faktb.id = fakta.id AND faktb.typ = 'FAKT'
LEFT OUTER JOIN vizman.FAKT faktc
	on faktc.id = fakta.id AND faktc.typ = 'SUB'
LEFT OUTER JOIN VIZMAN.KONT KONT
    ON zak.ID_KONT = KONT.ID
LEFT OUTER JOIN VIZMAN.KLIENT KLIENT
    ON KONT.ID_KLIENT = KLIENT.ID
GROUP BY zak.id
ORDER BY zak.id desc
;


