
-- !!!!  Do BEFORE tables are created:
SET COLLATION CZECH STRENGTH SECONDARY;


-- =============================================

DROP TABLE VIZMAN.CFGPROP;

CREATE TABLE VIZMAN.CFGPROP (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	VALUE VARCHAR(255),
	CONSTRAINT PK_CFGPROP PRIMARY KEY (NAME)
);

INSERT INTO VIZMAN.CFGPROP (ID, VERSION, NAME, VALUE)
VALUES(1, 1, 'app.locale', 'cs_CZ');

INSERT INTO VIZMAN.CFGPROP (ID, VERSION, NAME, VALUE)
VALUES(2, 1, 'project.root', 'projet-root-dir');

INSERT INTO VIZMAN.CFGPROP (ID, VERSION, NAME, VALUE)
VALUES(3, 1, 'document.root', 'document-root-dir');

INSERT INTO VIZMAN.CFGPROP (ID, VERSION, NAME, VALUE)
VALUES(4, 1, 'pojist.koef', '0.35r');

INSERT INTO VIZMAN.CFGPROP (ID, VERSION, NAME, VALUE)
VALUES(5, 1, 'rezie.koef', '0.8');


COMMIT;

-- =============================================

DROP TABLE VIZMAN.CIN;

CREATE TABLE VIZMAN.CIN (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	PORADI SMALLINT NOT NULL,
	CINT1 VARCHAR(2),
	CINT2 VARCHAR(2),
	AKCE VARCHAR(32),
	CINNOST VARCHAR(24),
	CALCPRAC BOOLEAN,
	TMP VARCHAR(1),
	CONSTRAINT PK_CIN PRIMARY KEY (PORADI)
);

INSERT INTO VIZMAN.CIN
(ID, VERSION, PORADI, CINT1, CINT2, AKCE, CINNOST, CALCPRAC, TMP)
SELECT CIN_ID, 1, PORADI, CIN_T1, CIN_T2, AKCE, CINNOST, CALCPRAC, TMP 
FROM ZAVIN.CIN_;

COMMIT;

-- =============================================

-- DROP TABLE VIZMAN.PERSON

CREATE TABLE VIZMAN.PERSON (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	STATUS VARCHAR(255),
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	JMENO VARCHAR(255),
	PRIJMENI VARCHAR(255),
	NASTUP DATE,
	VYSTUP DATE,
	SAZBA DECIMAL(19,2),
	CONSTRAINT PK_PERSON PRIMARY KEY (ID)
);

INSERT INTO VIZMAN.PERSON
(ID, VERSION, STATUS, JMENO, PRIJMENI, PASSWORD, USERNAME, NASTUP, VYSTUP, SAZBA)
VALUES(1001, 0, 'ACTIVE', 'Admin', 'Systemak', 'admin', 'admin', NULL, NULL, 0);
INSERT INTO VIZMAN.PERSON
(ID, VERSION, STATUS, JMENO, PRIJMENI, PASSWORD, USERNAME, NASTUP, VYSTUP, SAZBA)
VALUES(1002, 0, 'ACTIVE', 'User', 'Bìžný user', 'user', 'user', NULL, NULL, 0);

INSERT INTO VIZMAN.PERSON
(ID, VERSION, STATUS, JMENO, PRIJMENI, PASSWORD, USERNAME, NASTUP, VYSTUP, SAZBA, STATUS)
SELECT USER_ID, 1, 'ACTIVE, 'USER_FIRST, USER_LAST, USER_PWD, USER_LOGIN, USER_NASTUP, USER_VYSTUP, USER_SAZBA, USER_STATUS 
FROM ZAVIN.USR_;

COMMIT;


--  =============================================


CREATE TABLE VIZMAN."ROLE" (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255),
	CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);
-- CREATE UNIQUE INDEX IDXQ_PK_ROLE ON VIZMAN."ROLE" (ID);

INSERT INTO VIZMANDB.VIZMAN."ROLE" (ID, VERSION, DESCRIPTION, NAME)
VALUES(1, 1, 'Administrátor - všechna existující oprávnìní', 'ROLE_ADMIN');

INSERT INTO VIZMANDB.VIZMAN."ROLE" (ID, VERSION, DESCRIPTION, NAME)
VALUES(2, 1, 'Uživatel - bìžná oprávnìní½', 'ROLE_USER');

--  =============================================

-- DROP TABLE VIZMAN.PERSON_ROLE

CREATE TABLE VIZMAN.PERSON_ROLE (
	PERSON_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL,
	CONSTRAINT PK_PERSON_ROLE PRIMARY KEY (PERSON_ID,ROLE_ID),
	CONSTRAINT FK_PERSON_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES VIZMAN."ROLE"(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_PERSON_ROLE_PERSON FOREIGN KEY (PERSON_ID) REFERENCES VIZMAN.PERSON(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
-- CREATE UNIQUE INDEX IDXQ_PK_PERSON_ROLE ON VIZMAN.PERSON_ROLE (PERSON_ID,ROLE_ID);
-- CREATE INDEX IDX_FK_PERSON_ROLE_ROLE ON VIZMAN.PERSON_ROLE (ROLE_ID);
-- CREATE INDEX IDX_FK_PERSON_ROLE_PERSON ON VIZMAN.PERSON_ROLE (PERSON_ID);

--  =============================================

DROP TABLE VIZMAN.PODZAK;
DROP TABLE VIZMAN.ZAK;
COMMIT;

--CREATE TABLE VIZMAN.ZAK (
-- 	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
-- 	CZAK VARCHAR(30) NOT NULL,
-- 	TEXT VARCHAR(255),
-- 	FIRMA VARCHAR(30),
---- 	HONORAR DECIMAL(100,4) DEFAULT 0,
---- 	ROZPRAC DECIMAL(100,4) DEFAULT 0,
-- 	DATUMZAD TIMESTAMP,
-- 	ARCH BOOLEAN DEFAULT FALSE
--);
-- 
--CREATE UNIQUE INDEX PRIMARY_KEY_ZAK ON VIZMAN.ZAK (ID);


TRUNCATE TABLE vizman.zak;
DROP TABLE vizman.zak;

CREATE TABLE VIZMAN.ZAK (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	ARCH BOOLEAN,
	CZAK VARCHAR(255),
	DATUMZAD TIMESTAMP,
	FIRMA VARCHAR(255),
	TEXT VARCHAR(255),
	CONSTRAINT PK_ZAK PRIMARY KEY (ID)
);
CREATE INDEX IDX_ZAK_FIRMA ON VIZMAN.ZAK (FIRMA);
CREATE UNIQUE INDEX IDXQ_ZAK_CZAK ON VIZMAN.ZAK (CZAK);


COMMIT;

-- DROP SEQUENCE VIZMAN.ZAK_SEQ;
CREATE SEQUENCE IF NOT EXISTS VIZMAN.ZAK_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 1
 ;

INSERT INTO VIZMAN.ZAK (ID, VERSION, CZAK, TEXT, FIRMA, DATUMZAD, ARCH)
SELECT VIZMAN.ZAK_SEQ.NEXTVAL, 1, CISLO_ZAKAZKY, TEXT, FIRMA, DATUMIMP, ARCH FROM ZAVIN.ZAK_;

COMMIT;


--CREATE TABLE VIZMAN.PODZAK (
--	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
--	ID_ZAK BIGINT DEFAULT NOT NULL,
--	CZAK VARCHAR(30) NOT NULL,
--	ID_ZAKAZKY INT DEFAULT NOT NULL,
--	TYP_DOKLADU VARCHAR(2),
--	ROKZAK SMALLINT DEFAULT 0,
--	ROKMESZAD VARCHAR(7),
--	TEXT VARCHAR(255),
--	X BOOLEAN,
--	HONORAR DECIMAL(100,4) DEFAULT 0,
--	ROZPRAC DECIMAL(100,4) DEFAULT 0,
--	TMP VARCHAR(1),
--	ARCH BOOLEAN DEFAULT FALSE,
--	R_ZAL INTEGER DEFAULT 0,
--	R1 DECIMAL(5,1) DEFAULT 0,
--	R2 DECIMAL(5,1) DEFAULT 0,
--	R3 DECIMAL(5,1) DEFAULT 0,
--	R4 DECIMAL(5,1) DEFAULT 0,
--	SKUPINA VARCHAR(1),
--	RM DECIMAL(5,1) DEFAULT 0,
--);
--CREATE UNIQUE INDEX PRIMARY_KEY_ZAK ON VIZMAN.ZAK (ID);


TRUNCATE TABLE VIZMAN.PODZAK;

CREATE TABLE VIZMAN.PODZAK (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	ARCH BOOLEAN,
	CZAK VARCHAR(255),
	CPODZAK INTEGER,
	HONORAR DECIMAL(19,2),
	R1 DECIMAL(19,2),
	R2 DECIMAL(19,2),
	R3 DECIMAL(19,2),
	R4 DECIMAL(19,2),
	R_ZAL INTEGER,
	RM DECIMAL(19,2),
	ROKMESZAD VARCHAR(255),
	ROKZAK SMALLINT,
	ROZPRAC DECIMAL(19,2),
	SKUPINA VARCHAR(255),
	TEXT VARCHAR(255),
	TMP VARCHAR(255),
	TYP_DOKLADU VARCHAR(255),
	X BOOLEAN,
	ID_ZAK BIGINT,
	CONSTRAINT PK_PODZAK PRIMARY KEY (ID),
	CONSTRAINT FK_PODZAK_ZAK FOREIGN KEY (ID_ZAK) REFERENCES VIZMAN.ZAK(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
-- CREATE INDEX IDX_FK_PODZAK_ZAK ON VIZMAN.PODZAK (ID_ZAK);

COMMIT;

CREATE SEQUENCE IF NOT EXISTS VIZMAN.PODZAK_SEQ
  START WITH 1
  INCREMENT BY 1
  CACHE 1
 ;


INSERT INTO VIZMAN.PODZAK (ID, VERSION, CZAK, CPODZAK, TYP_DOKLADU,
                        ROKZAK, ROKMESZAD, TEXT, HONORAR, ROZPRAC, ARCH,
                        R_ZAL, R1, R2, R3, R4, SKUPINA, RM)
SELECT VIZMAN.PODZAK_SEQ.NEXTVAL, 1, CISLO_ZAKAZKY, 1, TYP_DOKLADU, ROKZAK, ROKMESZAD, TEXT, HONORAR, ROZPRAC, ARCH, R_ZAL, R1, R2, R3, R4, SKUPINA, RM
FROM ZAVIN.ZAK_;

COMMIT;


UPDATE VIZMAN.PODZAK AS pz
SET pz.ID_ZAK = (SELECT top 1 zak.ID FROM VIZMAN.ZAK zak
		WHERE pz.CZAK = zak.CZAK)
WHERE pz.CZAK IN (SELECT zak.CZAK from VIZMAN.ZAK zak where zak.CZAK = pz.CZAK)
;


CREATE UNIQUE INDEX IDXQ_PODZAK ON VIZMAN.PODZAK (CZAK, CPODZAK);


--update tlegacy lca set 
--  lca.pr_dato = (select ca.calc_holdings_date ... from tca ca where ...)
--  where lca.id in (select ca.id from tca where ...)


ALTER TABLE VIZMAN.PODZAK
ADD FOREIGN KEY (ID_ZAK) REFERENCES VIZMAN.ZAK(ID);

COMMIT;
