
DROP TABLE VIZMAN.KONT;
DROP TABLE VIZMAN.ZAK;
COMMIT;

--CREATE TABLE VIZMAN.KONT (
-- 	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
-- 	CISLO_KONTRAKTU VARCHAR(30) NOT NULL,
-- 	TEXT VARCHAR(255),
-- 	FIRMA VARCHAR(30),
---- 	HONORAR DECIMAL(100,4) DEFAULT 0,
---- 	ROZPRAC DECIMAL(100,4) DEFAULT 0,
-- 	DATUMZAD TIMESTAMP,
-- 	ARCH BOOLEAN DEFAULT FALSE
--);
-- 
--CREATE UNIQUE INDEX PRIMARY_KEY_KONT ON VIZMAN.KONT (ID);

CREATE TABLE VIZMAN.KONT (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	ARCH BOOLEAN,
	CISLO_KONTRAKTU VARCHAR(255),
	DATUMZAD TIMESTAMP,
	FIRMA VARCHAR(255),
	TEXT VARCHAR(255),
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON VIZMAN.KONT (ID);

COMMIT;
 
INSERT INTO VIZMAN.KONT (ID, VERSION, CISLO_KONTRAKTU, TEXT, FIRMA, DATUMZAD, ARCH)
SELECT VIZMAN.KONT_SEQ.NEXTVAL, 1, CISLO_ZAKAZKY, TEXT, FIRMA, DATUMIMP, ARCH FROM PUBLIC.ZAK_;

COMMIT;


--CREATE TABLE VIZMAN.ZAK (
--	ID BIGINT DEFAULT NOT NULL AUTO_INCREMENT,
--	ID_KONT BIGINT DEFAULT NOT NULL,
--	CISLO_ZAKAZKY VARCHAR(30) NOT NULL,
--	ID_ZAKAZKY INT DEFAULT NOT NULL,
--	TYP_DOKLADU VARCHAR(2),
--	ROKZAK SMALLINT DEFAULT 0,
--	ROKMESZAD VARCHAR(7),
--	TEXT VARCHAR(255),
--	X BOOLEAN,
--	HONORAR DECIMAL(100,4) DEFAULT 0,
--	ROZPRAC DECIMAL(100,4) DEFAULT 0,
--	TMP VARCHAR(1),
--	ARCH BOOLEAN DEFAULT FALSE,
--	R_ZAL INTEGER DEFAULT 0,
--	R1 DECIMAL(5,1) DEFAULT 0,
--	R2 DECIMAL(5,1) DEFAULT 0,
--	R3 DECIMAL(5,1) DEFAULT 0,
--	R4 DECIMAL(5,1) DEFAULT 0,
--	SKUPINA VARCHAR(1),
--	RM DECIMAL(5,1) DEFAULT 0,
--);
--CREATE UNIQUE INDEX PRIMARY_KEY_ZAK ON VIZMAN.ZAK (ID);


CREATE TABLE VIZMAN.ZAK (
	ID BIGINT NOT NULL,
	VERSION INTEGER NOT NULL,
	ARCH BOOLEAN,
	CISLO_ZAKAZKY VARCHAR(255),
	HONORAR DECIMAL(19,2),
	ID_ZAKAZKY INTEGER,
	R1 DECIMAL(19,2),
	R2 DECIMAL(19,2),
	R3 DECIMAL(19,2),
	R4 DECIMAL(19,2),
	R_ZAL INTEGER,
	RM DECIMAL(19,2),
	ROKMESZAD VARCHAR(255),
	ROKZAK SMALLINT,
	ROZPRAC DECIMAL(19,2),
	SKUPINA VARCHAR(255),
	TEXT VARCHAR(255),
	TMP VARCHAR(255),
	TYP_DOKLADU VARCHAR(255),
	X BOOLEAN,
	ID_KONT BIGINT,
	CONSTRAINT CONSTRAINT_15 PRIMARY KEY (ID),
	CONSTRAINT FKB32J8O4E2DSWWI71UGCM59B9H FOREIGN KEY (ID_KONT) REFERENCES VIZMAN.KONT(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKB32J8O4E2DSWWI71UGCM59B9H_INDEX_1 ON VIZMAN.ZAK (ID_KONT);
CREATE UNIQUE INDEX PRIMARY_KEY_15 ON VIZMAN.ZAK (ID);

COMMIT;


INSERT INTO VIZMAN.ZAK (ID, VERSION, CISLO_ZAKAZKY, ID_ZAKAZKY, TYP_DOKLADU,
                        ROKZAK, ROKMESZAD, TEXT, HONORAR, ROZPRAC, ARCH,
                        R_ZAL, R1, R2, R3, R4, SKUPINA, RM)
SELECT VIZMAN.ZAK_SEQ.NEXTVAL, 1, CISLO_ZAKAZKY, 1, TYP_DOKLADU, ROKZAK, ROKMESZAD, TEXT, HONORAR, ROZPRAC, ARCH, R_ZAL, R1, R2, R3, R4, SKUPINA, RM
FROM PUBLIC.ZAK_;

COMMIT;


UPDATE VIZMAN.ZAK AS z
SET z.ID_KONT = (SELECT top 1 k.ID FROM VIZMAN.KONT k
		WHERE z.CISLO_ZAKAZKY = k.CISLO_KONTRAKTU)
WHERE z.CISLO_ZAKAZKY IN (SELECT k.CISLO_KONTRAKTU from VIZMAN.KONT k where k.CISLO_KONTRAKTU = z.CISLO_ZAKAZKY)
;


CREATE UNIQUE INDEX IDX_ZAK ON VIZMAN.ZAK (CISLO_ZAKAZKY, ID_ZAKAZKY);


--update tlegacy lca set 
--  lca.pr_dato = (select ca.calc_holdings_date ... from tca ca where ...)
--  where lca.id in (select ca.id from tca where ...)


ALTER TABLE VIZMAN.ZAK
ADD FOREIGN KEY (ID_KONT) REFERENCES VIZMAN.KONT(ID);

COMMIT;
